DatabaseConsistencySettings:
  color: true

Event:
  code_name:
    MissingUniqueIndexChecker:
      enabled: false

Permission:
  event:
    ForeignKeyChecker:
      enabled: false

User:
  email:
    ColumnPresenceChecker:
      enabled: false
  password:
    ColumnPresenceChecker:
      enabled: false
  index_users_on_reset_password_token:
    UniqueIndexChecker:
      enabled: false
